# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourapp', '0003_auto_20181022_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_pics')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
